name: generate animation

on:
  # Ejecutar automáticamente cada 12 horas
  schedule:
    - cron: "0 */12 * * *"
  
  # Permite ejecutar el trabajo manualmente en cualquier momento
  workflow_dispatch:
  
  # Ejecutar en cada push en la rama main
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      # Genera un juego de serpiente desde el gráfico de contribuciones de un usuario de GitHub, genera una animación SVG en el directorio dist
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v2
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # Sube el contenido de build_dir a una rama
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
